FROM nginx:1.15.0-alpine

RUN apk update && \
  apk add --no-cache wget && \
  wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.4/wait-for && \
  chmod +x /usr/bin/wait-for


RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

COPY start.sh /user/bin/start.sh
RUN chmod +x /user/bin/start.sh

EXPOSE 80