FROM node:16

RUN apt-get clean

RUN apt-get update && \
  apt-get install -y wget && \
  apt-get -qy install netcat && \
  wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.4/wait-for && \
  chmod +x /usr/bin/wait-for

WORKDIR /usr/src/app

COPY . .

RUN chown -R node:node /usr/src/app
RUN chmod +x start.sh
RUN chown -R node:node start.sh
RUN chown -R 1000:1000 "/root/.npm"

CMD ["./start.sh"]

EXPOSE 3000